name: 'MQTT Publish Action'
description: 'This action publishes a MQTT message from GitHub Actions.'
author: 'Joachim Uhrlaß'
inputs:
  protocol:
    description: "MQTT server protocol. One of: 'wss' | 'ws' | 'mqtt' | 'mqtts' | 'tcp' | 'ssl' | 'wx' | 'wxs'"
    default: 'mqtt'
    required: true
  host:
    description: 'MQTT server host'
    default: 'localhost'
    required: true
  port:
    description: 'MQTT server port'
    default: 1883
    required: true
  topic:
    description: 'MQTT topic'
    required: true
  qos:
    description: "Quality of Service. One of: '0' | '1'"
    default: 0
    required: true
  retain:
    description: "Retain message"
    required: true
    default: false
  username:
    description: 'MQTT username'
    required: false
  password:
    description: 'MQTT password'
    required: false
  message:
    description: 'Message to send'
    required: true
runs:
  using: 'node12'
  main: 'app.js'
 # main: 'dist/index.js'
branding:
  icon: 'cast'
  color: 'gray-dark'
